version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo "No build step for this app"
  post_build:
    commands:
      - echo Build completed...
artifacts:
  files:
    - '**/*'
  base-directory: .
