version: 0.2
phases:
  install:
    commands:
      - echo Using Dockerfile build; no dependencies to install
  build:
    commands:
      - echo No build step needed
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  base-directory: .
